/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.roggi.console.application

import ru.roggi.console.application.scene.Scene
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Scene()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
